version: "3.8"

networks:
    goldenpot_lan:
      ipam:
        config:
          - subnet: 172.18.0.0/8


services:
  website:
      build:
          context: ./website
      ports:
        - 80:80
      networks:
        goldenpot_lan:
          ipv4_address: 172.18.0.2
  
  setup_test:
    build:
      context: ./setup
    networks:
      goldenpot_lan:
        ipv4_address: 172.18.0.3

  goldenpot:
    build:
      context: ./users
    ports:
      - 22:22
    networks:
      goldenpot_lan:
        ipv4_address: 172.18.0.4

  db:
    build:
      context: ./db
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      goldenpot_lan:
        ipv4_address: 172.18.0.5