version: "3.8"

networks:
    goldenpot:
      ipam:
        config:
          - subnet: 172.18.0.0/16


services:
  website:
      build:
          context: ./website
      ports:
        - 80:80
      networks:
        goldenpot:
          ipv4_address: 172.18.0.2
  
  setup_test:
    build:
      context: ./setup
    networks:
      goldenpot:
        ipv4_address: 172.18.0.3

  goldenpot:
    build:
      context: ./users
    ports:
      - 22:22
    networks:
      ipv4_address: 172.18.0.4
