version: "3.8"

networks:
    world-company-network:
      ipam:
        config:
          - subnet: 172.18.0.0/16


services:
  wordpress:
      image: wordpress
      restart: always
      ports:
        - 80:80
      environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_USER: exampleuser
        WORDPRESS_DB_PASSWORD: examplepass
        WORDPRESS_DB_NAME: exampledb
      volumes:
        - wordpress:/var/www/html
      networks:
        world-company-network:
          ipv4_address: 172.18.0.2

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
        world-company-network:
          ipv4_address: 172.18.0.3

volumes:
  wordpress:
  db: